routes/web.php
<?php

use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Artisan;

Route::get('/', 'Home\HomeController@index');

//  Route untuk Master
Route::middleware(['isLogin', 'isNonTenant'])->group(function () {

    Route::get('dashboard', 'Dashboard\DashboardController@index');

    Route::get('tenant', 'Tenant\TenantController@index');
    Route::get('tenant/create', 'Tenant\TenantController@create');
    Route::post('tenant/store', 'Tenant\TenantController@store');
    Route::get('tenant/{id}', 'Tenant\TenantController@show');
    Route::get('tenant-enabled/{id}', 'Tenant\TenantController@enableTenant');
    Route::get('tenant-disabled/{id}', 'Tenant\TenantController@disableTenant');
    Route::get('tenant/{id}/edit', 'Tenant\TenantController@edit');
    Route::put('tenant/{id}/update', 'Tenant\TenantController@update');


    Route::get('admin', 'Admin\AdminController@index');
    Route::get('admin/create', 'Admin\AdminController@create');
    Route::post('admin/store', 'Admin\AdminController@store');
    Route::get('admin/{email}', 'Admin\AdminController@show');
    Route::get('admin-enabled/{email}', 'Admin\AdminController@enableAdmin');
    Route::get('admin-disabled/{email}', 'Admin\AdminController@disableAdmin');
    Route::get('admin/edit/{email}', 'Admin\AdminController@edit');


});

// Route untuk Client ataupun Tenant
Route::middleware(['isLogin', 'isTenant'])->group(function () {

    Route::get('beranda', 'Beranda\BerandaController@index');

    Route::resource('branches', 'Branches\BranchesController');
    Route::get('branches-enabled/{email}', 'Branches\BranchesController@enableBranch');
    Route::get('branches-disabled/{email}', 'Branches\BranchesController@disableBranch');

    Route::resource('employee', 'Employee\EmployeeController');

    Route::resource('roles', 'Role\RoleController');


});

// Route untuk logout
Route::middleware(['isLogin'])->group(function () {

    Route::any('logout', 'Auth\logoutController@logoutUser');
    Route::get('account', 'Account\AccountController@index');
    Route::post('account/change-password', 'Account\AccountController@changePassword');

});

//  Route untuk login and Register
Route::middleware(['isNotLogin'])->group(function () {

    // Route::get('/register', 'Auth\RegisterController@index');
    // Route::post('/register', 'Auth\RegisterController@postRegister');

    Route::get('login', 'Auth\LoginController@index');
    Route::post('login', 'Auth\LoginController@postLogin');

    Route::post('forgot-password', 'Auth\ForgotPasswordController@forgotPassword');

    Route::get('reset-password/{email}/{reminderCode}', 'Auth\ResetPasswordController@resetPassword');
    Route::post('reset-password', 'Auth\ResetPasswordController@postResetPassword');

    Route::get('change-password', 'Auth\ChangePasswordController@changePassword');

    ROute::get('testing', 'Testing\TestingController@assignRoleToUser');
});

app/Models/Master/User/UserMasterModel.php
<?php

namespace App\Models\Master\User;

use Cartalyst\Sentinel\Users\EloquentUser;
use App\Models\Tenant\UserTenant\UserTenantModel;
use Sentinel as Auth;

class UserMasterModel extends EloquentUser
{
    protected $connection = 'mysql_master';

    protected $table = 'ms_users';

    protected $fillable = [
        'username',
        'email',
        'password',
        'first_name',
        'middle_name',
        'last_name',
        'permissions',
        'last_login',
        'api_token'
    ];

    protected $loginNames = ['email', 'username'];

    protected static $rolesModel = 'App\Models\Master\User\RoleModel';

    protected static $persistencesModel = 'App\Models\Master\User\PersistenceModel';

    protected static $activationsModel = 'App\Models\Master\User\ActivationModel';

    protected static $remindersModel = 'App\Models\Master\User\ReminderModel';

    protected static $throttlingModel = 'App\Models\Master\User\ThrottleModel';

    protected static $descriptionUserModel = 'App\Models\Master\DescriptionUser\DescriptionUserModel';

    protected static $userTenant  = 'App\Models\Tenant\UserTenant\UserTenantModel';

    public function roles()
    {
        return $this->belongsToMany(static::$rolesModel, 'ms_role_users', 'user_id', 'role_id')->withTimestamps();
    }

    public function persistences()
    {
        return $this->hasMany(static::$persistencesModel, 'user_id');
    }

    public function activations()
    {
        return $this->hasMany(static::$activationsModel, 'user_id');
    }

    public function reminders()
    {
        return $this->hasMany(static::$remindersModel, 'user_id');
    }

    public function throttle()
    {
        return $this->hasMany(static::$throttlingModel, 'user_id');
    }

    public function description_user()
    {
        return $this->hasOne(static::$descriptionUserModel, 'user_id')
        ->withDefault([
            'description' => 'User Master'
        ]);
    }

    public function user_tenant()
    {
        return $this->hasOne(UserTenantModel::class, 'user_id', 'id');
    }

    public function getFullNameAttribute() {
        return "{$this->first_name} {$this->middle_name} {$this->last_name}";
    }

    public function getTenantIdAttribute() {

        return Auth::getUser()->description_user->tenant_id ?? '';
    }

    public function createRole() {
        return Auth::getRoleRepository()->createModel();
    }
}

resources/views/admin/create_admin.blade.php
@extends('layout.app')

@section('css')

@endsection

@section('content')
    <div class="row page-titles">

        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">Tambah Admin/Penyewa Baru</h4>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    @if (session('error'))
                        @include('ui.alert.alert_danger', [
                            'message' => session('error')
                        ])
                    @endif

                    <form action="/admin/store" method="POST" autocomplete="off">

                        <div class="row justify-content-center mt-5">

                            @csrf

                            <div class="col-md-3">

                                {{-- First Name --}}
                                @include('ui.input.input_tag', [
                                    'label' => 'Nama Depan',
                                    'id' => 'first_name',
                                    'name' => 'first_name',
                                    'placeholder' => 'Nama Depan',
                                ])

                                {{-- Middle Name --}}
                                @include('ui.input.input_tag', [
                                    'label' => 'Nama Tengah',
                                    'id' => 'middle_name',
                                    'name' => 'middle_name',
                                    'placeholder' => 'Nama Tengah',
                                ])

                                {{-- Last Name --}}
                                @include('ui.input.input_tag', [
                                    'label' => 'Nama Belakang',
                                    'id' => 'last_name',
                                    'name' => 'last_name',
                                    'placeholder' => 'Nama Belakang',
                                ])

                                {{-- Tenant --}}
                                @include('ui.input.select_tag', [
                                    'label' => 'Nama Tenant',
                                    'id' => 'tenant_id',
                                    'name' => 'tenant_id',
                                    'options' => $tenant
                                ])

                                {{-- Address --}}
                                @include('ui.input.textarea', [
                                    'label' => 'Alamat',
                                    'id' => 'address',
                                    'name' => 'address',
                                    'placeholder' => 'Alamat'
                                ])

                            </div>

                            <div class="col-md-3">

                                {{-- Username --}}
                                @include('ui.input.input_tag', [
                                    'label' => 'Username',
                                    'id' => 'username',
                                    'name' => 'username',
                                    'placeholder' => 'Username',
                                ])

                                {{-- Email --}}
                                @include('ui.input.input_tag', [
                                    'label' => 'Email',
                                    'type' => 'email',
                                    'id' => 'email',
                                    'name' => 'email',
                                    'placeholder' => 'Email',
                                ])

                                {{-- Password --}}
                                @include('ui.input.input_tag', [
                                    'label' => 'Password',
                                    'type' => 'password',
                                    'id' => 'password',
                                    'name' => 'password',
                                    'placeholder' => 'Password',
                                ])

                                {{-- Password Confirmation--}}
                                @include('ui.input.input_tag', [
                                    'label' => 'Konfrimasi Password',
                                    'type' => 'password',
                                    'id' => 'password_confirmation',
                                    'name' => 'password_confirmation',
                                    'placeholder' => 'Password',
                                ])

                                {{-- Deskripsi --}}
                                @include('ui.input.textarea', [
                                    'label' => 'Deskripsi',
                                    'id' => 'description',
                                    'name' => 'description',
                                    'placeholder' => 'Deskripsi'
                                ])

                                <div class="float-right mt-2">
                                    <button class="btn btn-info" type="submit">Kirim</button>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

@endsection

@section('js')

@endsection

resources/views/admin/edit_admin.blade.php
@extends('layout.app')

@section('css')

@endsection

@section('content')
    <p>
        {{$userAdmin}}
    </p>
@endsection

@section('js')

@endsection

resources/views/admin/index_admin.blade.php
@extends('layout.app')

@section('css')

@endsection

@section('content')

    <div class="row page-titles">

        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">List Admin Penyewa/Tenant</h4>
        </div>

        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <a class="btn btn-info d-none d-lg-block m-l-15"
                href="admin/create"><i class="fa fa-plus-circle"></i> Tambah Admin Penyewa Baru</a>
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    @if (session('success'))
                        @include('ui.alert.alert_success', ['message' => session('success')])
                    @endif

                    @if (session('error'))
                        @include('ui.alert.alert_danger', ['message' => session('error')])
                    @endif

                    <h4 class="card-title">Daftar Admin Penyewa/Tenant</h4>

                    <div class="mt-5 table-responsive">
                        <table class="table table-bordered table-hover">

                            <thead>
                                <tr>
                                    <th class="text-center">No</th>
                                    <th>Nama</th>
                                    <th>Email</th>
                                    <th>Deskripsi</th>
                                    <th>Nama Tenant</th>
                                    <th class="text-center">Opsi</th>
                                </tr>
                            </thead>

                            <tbody>
                                @forelse ($userAdmin as $user)
                                    @if ($user->hasAccess(['user.tenant','user.admin.tenant']))
                                        <tr>
                                            <td class="text-center">{{$user->id}}</td>
                                            <td>{{$user->full_name}}</td>
                                            <td>{{$user->email}}</td>
                                            <td>{{$user->description_user->description}}</td>
                                            <td>{{$user->description_user->tenant_master->name}}</td>
                                            <td class="text-center">
                                                <a href="/admin/{{$user->email}}" class="btn btn-info btn-sm">
                                                    <i class="fas fa-info-circle"></i> Lihat
                                                </a>

                                                @if ($user->description_user->is_active)

                                                    <a href="/admin-disabled/{{$user->email}}" class="btn btn-danger btn-sm">
                                                        <i class="fas fa-ban"></i> Non-Aktifkan
                                                    </a>

                                                @else

                                                    <a href="/admin-enabled/{{$user->email}}" class="btn btn-success btn-sm">
                                                        <i class="fas fa-photo"></i> Aktifkan
                                                    </a>

                                                @endif
                                            </td>
                                        </tr>
                                    @endif
                                @empty
                                <tr>
                                    <td colspan="7" class="text-center">
                                        Belum Ada Admin Tersedia
                                    </td>
                                </tr>
                                @endforelse
                            </tbody>

                        </table>
                    </div>

                    <div class="float-right">
                        {{$userAdmin->links()}}
                    </div>


                </div>
            </div>
        </div>
    </div>

@endsection

@section('js')
    <script>
        var result = @json($userAdmin);
        console.log(result);

    </script>
@endsection

resources/views/admin/show_admin.blade.php
@extends('layout.app')

@section('css')

@endsection

@section('content')

    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="card-title"><i class="fas fa-sitemap"></i> Nama Admin : {{$adminTenant->full_name}}</h4>
        </div>

        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <a class="btn btn-info d-none d-lg-block m-l-15"
                href="/admin/edit/{{$adminTenant->email}}"><i class="fa fa-plus-circle"></i> Ubah </a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">

                <div class="card-header bg-success">
                    <h4 class="m-b-0 text-white">Info Admin</h4>
                </div>

                <div class="class-body">

                    <div class="mx-5">
                        <div class="row mt-3">

                            <div class="col-md-6">
                                @include('admin.ui_show_admin', [
                                    'label' => 'Nama Depan',
                                    'data' => $adminTenant->first_name
                                ])

                                @include('admin.ui_show_admin', [
                                    'label' => 'Nama Tengan',
                                    'data' => $adminTenant->middle_name ?? ''
                                ])

                                @include('admin.ui_show_admin', [
                                    'label' => 'Nama Belakang',
                                    'data' => $adminTenant->last_name
                                ])

                                @include('admin.ui_show_admin', [
                                    'label' => 'Username',
                                    'data' => $adminTenant->username
                                ])

                                @include('admin.ui_show_admin', [
                                    'label' => 'Email',
                                    'data' => $adminTenant->email
                                ])

                                @include('admin.ui_show_admin', [
                                    'label' => 'Password',
                                    'data' => "**********"
                                ])
                            </div>

                            <div class="col-md-6">
                                @include('admin.ui_show_admin', [
                                    'label' => 'Tenant',
                                    'data' => $adminTenant->description_user->tenant_master->name
                                ])

                                @include('admin.ui_show_admin', [
                                    'label' => 'Tenant Kode',
                                    'data' => $adminTenant->description_user->tenant_master->code
                                ])

                                @include('admin.ui_show_admin', [
                                    'label' => 'Deskripsi Admin',
                                    'data' => $adminTenant->description_user->description
                                ])

                                @include('admin.ui_show_admin', [
                                    'label' => 'Status',
                                    'data' => $adminTenant->description_user->is_active ? 'Admin Aktif' : 'Tidak aktif'
                                ])
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>

@endsection

@section('js')

@endsection

resources/views/admin/ui_show_admin.blade.php
<div class="form-group row">
    <label class="control-label text-right col-md-4">
        <div class="float-left">
            <h5 class="card-title">{{$label}} :</h5>
        </div>
    </label>
    <div class="col-md-8">
        <h5 class="card-title form-control-static">
            <span class=" py-1 px-3 border border-success rounded">{{$data ?? '-'}}</span>
        </h5>
    </div>
</div>